version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: the_bar
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: the_bar
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
